env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- binary: redli
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
    - s390x
  ignore:
    - goos: darwin
      goarch: s390x
    - goos: windows
      goarch: s390x
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
env_files:
  github_token: ~/.config/goreleaser/github_token
